name: 'Deploy'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install worker dependencies
        run: bun install --frozen-lockfile
      - name: Deploy
        run: |
          cd proxy
          bun run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          COMMITS_KEY: ${{ secrets.COMMITS_KEY }}
  build_search_index:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install worker dependencies
        run: bun install --frozen-lockfile
      - name: Build search index
        run: |
          cd proxy
          bun run createSearchIndex
        env:
          TYPESENSE_ADMIN_TOKEN: ${{ secrets.TYPESENSE_ADMIN_TOKEN }}
          TYPESENSE_HOST: ${{ secrets.TYPESENSE_HOST }}
